# Generated by Django 5.2.6 on 2025-09-30 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('recibido_por', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('diagnostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='diagnostico.diagnostico')),
            ],
        ),
    ]
