# Generated by Django 5.2.6 on 2025-10-03 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibido_por', models.CharField(max_length=150)),
                ('documento_receptor', models.CharField(max_length=50)),
                ('observaciones_entrega', models.TextField(blank=True, null=True)),
                ('cliente_satisfecho', models.BooleanField(default=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='recepcion.equipo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
