# Generated by Django 5.2.6 on 2025-10-17 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
        ('recepcion', '0004_alter_trazaequipo_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroTerceroConfirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor_nombre', models.CharField(max_length=150)),
                ('receptor_documento', models.CharField(max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=6)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('expirado', 'Expirado')], default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('responded_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion_retiro', to='recepcion.equipo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
