"""
Django settings for gestion_clinica project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import importlib.util
import logging
import warnings
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde el archivo .env
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-6#wbqw$*tr*%!$#ow=1ny=u@zk7j*_$!j337$-&x2_u8gvl7+f')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login_app',
    'recepcion',
    'diagnostico',
    'entrega',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # ⚡ importante
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


ROOT_URLCONF = 'gestion_clinica.urls'

from pathlib import Path
import os


STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # 👈 agrega esta línea
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'gestion_clinica.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configuración de base de datos (cumple rúbrica: PostgreSQL por variables de entorno; fallback SQLite)
DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()  # valores: 'postgres' | 'sqlite'

if DB_ENGINE == 'postgres':
    def _ensure_postgres_driver() -> str:
        """Return the first available PostgreSQL driver or raise an explicit error."""

        for driver in ('psycopg', 'psycopg2'):
            if importlib.util.find_spec(driver):
                return driver

        raise ImproperlyConfigured(
            "Se configuró DB_ENGINE=postgres pero no se encontró el controlador de PostgreSQL. "
            "Instala la dependencia ejecutando 'pip install psycopg[binary]' (o 'pip install -r requirements.txt'). "
            "Como alternativa temporal para desarrollo local, establece DB_ENGINE=sqlite en tu archivo .env."
        )

    POSTGRES_DRIVER = _ensure_postgres_driver()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'clinica_pc'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {**({'sslmode': os.getenv('DB_SSLMODE', 'prefer')} if os.getenv('DB_SSLMODE') else {})},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

# Mostrar fechas en la zona horaria de Chile
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'   # 👈 así

# ============================================
# 📧 CONFIGURACIÓN DE EMAIL MEJORADA Y ROBUSTA
# ============================================

# Seleccionar el proveedor de email activo desde variables de entorno
EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', 'gmail').lower()

# Configuración común
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_TIMEOUT = 30  # Timeout aumentado para conexiones lentas
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# 🔧 Configuraciones por proveedor
if EMAIL_PROVIDER == 'gmail':
    # Gmail (requiere contraseña de aplicación)
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'tu-email@gmail.com')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'tu-contraseña-de-aplicacion')
    
elif EMAIL_PROVIDER == 'outlook':
    # Outlook/Hotmail (más estable para envíos masivos)
    EMAIL_HOST = 'smtp-mail.outlook.com'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'tu-email@outlook.com')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'tu-contraseña')
    
elif EMAIL_PROVIDER == 'yahoo':
    # Yahoo Mail
    EMAIL_HOST = 'smtp.mail.yahoo.com'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'tu-email@yahoo.com')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'tu-contraseña-de-aplicacion')
    
elif EMAIL_PROVIDER == 'console':
    # Para desarrollo - muestra emails en consola
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST_USER = 'desarrollo@clinicapc.com'
    
else:
    # Configuración por defecto (Gmail)
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'tu-email@gmail.com')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'tu-contraseña-de-aplicacion')

# Email remitente por defecto
DEFAULT_FROM_EMAIL = f'Clínica PC <{EMAIL_HOST_USER}>'
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# 🚀 CONFIGURACIÓN AVANZADA DE RENDIMIENTO
EMAIL_FAIL_SILENTLY = False  # Para detectar errores
EMAIL_MAX_RETRIES = 3  # Número de reintentos
EMAIL_RETRY_DELAY = 5  # Segundos entre reintentos
