# Generated by Django 5.2.6 on 2025-10-03 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('Laptop', 'Laptop'), ('PC Escritorio', 'PC Escritorio'), ('All-in-One', 'All-in-One'), ('Tablet', 'Tablet'), ('Servidor', 'Servidor'), ('Otro', 'Otro')], max_length=80)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('problema', models.TextField(blank=True)),
                ('accesorios', models.JSONField(blank=True, default=list)),
                ('observaciones_adicionales', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('recepcion', 'Recepción'), ('diagnostico', 'Diagnóstico'), ('hardware', 'Reparación Hardware'), ('software', 'Reparación Software'), ('reparacion', 'En Reparación'), ('despacho', 'Listo para Despacho'), ('entregado', 'Entregado')], default='recepcion', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='recepcion.cliente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
