# Generated by Django 5.2.6 on 2025-10-03 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='caja_cliente',
            field=models.TextField(blank=True, help_text='Descripción de accesorios/objetos en caja del cliente'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='caja_equipo',
            field=models.TextField(blank=True, help_text='Descripción del estado del equipo recibido'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='observaciones_recepcionista',
            field=models.TextField(blank=True, help_text='Observaciones del recepcionista'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='relato_cliente',
            field=models.TextField(blank=True, help_text='Relato exacto del cliente sin edición'),
        ),
        migrations.CreateModel(
            name='TrazaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ingreso', 'Ingreso al sistema'), ('diagnostico', 'Enviado a diagnóstico'), ('hardware', 'Enviado a reparación hardware'), ('software', 'Enviado a reparación software'), ('despacho', 'Listo para despacho'), ('entregado', 'Equipo entregado'), ('observacion', 'Observación agregada')], max_length=20)),
                ('descripcion', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazas', to='recepcion.equipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
