# Generated by Django 5.2.6 on 2025-10-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_cliente_ciudad_equipo_caja_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen_carnet',
            field=models.ImageField(blank=True, help_text='Imagen del carnet del cliente por seguridad', null=True, upload_to='carnets/'),
        ),
    ]
