# Generated by Django 5.2.6 on 2025-10-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_cliente_imagen_carnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazaequipo',
            name='accion',
            field=models.CharField(choices=[('ingreso', 'Ingreso al sistema'), ('diagnostico', 'Enviado a diagnóstico'), ('hardware', 'Enviado a reparación hardware'), ('software', 'Enviado a reparación software'), ('hardware_to_software', 'Enviado de Hardware a Software'), ('software_to_hardware', 'Enviado de Software a Hardware'), ('despacho', 'Listo para despacho'), ('entregado', 'Equipo entregado'), ('observacion', 'Observación agregada')], max_length=20),
        ),
    ]
