# Generated by Django 5.1.2 on 2025-10-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='observacion_urgente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
